### ISSUE TITLE
MariaDB won't connect (Synology NAS; Docker via SSH)

### ISSUE THREAD

**Issue by 0n1cOn3** [mhzawadi/invoiceplane#12]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* please explain your *feature* or *bug* report
>  Set up the image according to the instructions. Invoicemail cannot connect to the database even though the port is enabled (manually). 

* **What is the current behavior?**

> Invoicemail cannot connect to the database even though the port is enabled (manually).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

> Follow the instructions as shown
> customize the web port from 80 to something else cuz DSM use it for the reverse proxy

* **What is the expected behavior?**

> Setup Invoicemail - and finish the simple db setup

* **What is the motivation / use case for changing the behavior?**
> Propably using a NAS with Docker :P 

* **Please tell us about your environment:**
  
> PC: Fedora 35
> NAS: 
SSH System Info: Linux <NASNAME>t 4.4.180+ #42218 SMP Mon Oct 18 19:17:56 CST 2021 x86_64 GNU/Linux synology_apollolake_218+
OS: DSM 7.0.1-42218 Update 2

  > Latest Docker Image
  > Browser: [ Firefox 98.0 64Bit]

**Comment by mhzawadi** [comment]
Hello @0n1cOn3,

Could you please provide the commands you used?

If you changed the ports, did you change both port 80 or just the lefthand?

**Comment by 0n1cOn3** [comment]
Hello @mhzawadi 

Iv changed the port on the client side of docker (Docker internal stays on 80) 

Afaik is the provided guide to setup invoicemail.

**Comment by mhzawadi** [comment]
Hey @0n1cOn3

turns out my image may be bust, investing now. will let you know when it works

**Comment by mhzawadi** [comment]
Hi @0n1cOn3 

I have done some testing and have got things working, but to be sure Im not adding things I dont need to could you try something please?

could you create a database in the mysql container? 
this can be done by either logging into the mysql container or using my [phpmyadmin](https://github.com/mhzawadi/phpmyadmin) image

**Comment by mhzawadi** [comment]
Hi @0n1cOn3 

I have updated the readme with MySQL options to create a database, this was the magic to get invoiceplane setup.

All tested on my mac and all updates will be going live this evening

**Comment by 0n1cOn3** [comment]
Will give a shot and will report if it has been fixed & close the ticket.

**Comment by mhzawadi** [comment]
please reopen if you still have issues

**Comment by 0n1cOn3** [comment]
I had not the time yet to get it done. 
But yup, would reopen if I will face the same issue. Thanks 😊
