### ISSUE TITLE
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by KevoM** [mhzawadi/invoiceplane#15]
* **I'm submitting a ...**
  - [ ] bug report

Hey, i'm trying to install invoiceplan to the RPi 4, i'm not an expert but I don't really know where I misunderstand your Readme

* **What is the current behavior?**
I'm getting this error "ERROR: no matching manifest for linux/arm/v7 in the manifest list entries"

* **What is the expected behavior?**
Docker compose up would install the containers

**Comment by mhzawadi** [comment]
Hi @KevoM 

Ive had a look at the image and the armv7 seems to work, it that the `docker run` command you get the error?

Saying that, I think you may have issues with MySQL. I cant find any MySQL or mariaDB that works on armv7 now

you may have to install mariadb on your pi

**Comment by mhzawadi** [comment]
please reopen if you still have issues
