### ISSUE TITLE
Can't submit setup page

### ISSUE THREAD

**Issue by khashashin** [mhzawadi/invoiceplane#16]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* ** please explain your *feature* or *bug* report**
I've deployed your docker image by using docker compose successfully. The database is hosted externally, so it creates the tables without any problems. I can get in to configuration view. After entering username and password I get following error on submit:
![image](https://user-images.githubusercontent.com/17837758/198912777-a26d7ac8-ec0c-454f-91e9-f4e179f5705b.png)

* **Please tell us about your environment:**
  
  - Version: image: mhzawadi/invoiceplane:latest

**Comment by nielsdrost7** [comment]
@khashashin which PHP version are you using?

**Comment by khashashin** [comment]
is it not defined in the docker? https://github.com/mhzawadi/invoiceplane/blob/1136e6c66fe9c5321658d7d98ca7e84e31929d9c/Dockerfile#L5

**Comment by nielsdrost7** [comment]
You're right, but usually these errors come from some weird PHP version, that's why I doublechecked

**Comment by khashashin** [comment]
I've fixed this error by installing following php extensions:
```
RUN apk add --no-cache --purge -uU nginx php7-fpm php7-xmlreader php7-curl php7-dom php7-xml php7-pdo_mysql \
    php7-xmlwriter php7-tokenizer php7-exif php7-simplexml php7-gd php7-gmp php7-bcmath php7-fileinfo \
    php7-posix php7-json php7-gettext php7-zlib php7-pcntl php7-mysqli php7-sockets php7-ctype php7-mysqlnd \
    php7-openssl php7-zip php7-pecl-mcrypt php7-xmlrpc php7-session composer curl unzip
```

**Comment by fr3d02** [comment]
Hello, i've same problèm but solution by khashashin don't resolve ? Can you help me ?
