### ISSUE TITLE
Unable to Access Invoiceplane using the provided .yml file.

### ISSUE THREAD

**Issue by adojang** [mhzawadi/invoiceplane#24]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* ** please explain your *feature* or *bug* report**

On windows 10, using the docker desktop app:
I downloaded this
curl https://github.com/mhzawadi/invoiceplane/blob/master/docker-compose.yml

and did:

docker-compose up -d

I can see traefik's dashboard, but cannot access invoiceplane anywhere.
I'm still new to docker, so perhaps I'm just missing something.

![image](https://github.com/mhzawadi/invoiceplane/assets/48274045/1fd42f38-45a2-4e51-a976-7f673db905a2)

**Comment by adojang** [comment]
When accessing localhost (127.0.0.1) see a plaintext html page that says:

"404 page not found"

**Comment by mhzawadi** [comment]
Hi @adojang 

Looks like I need some more notes on how the compose file works, you will need to add `invoiceplane.docker.local` to your hosts file so your browser knows where to find invoiceplane

**Comment by mhzawadi** [comment]
Hi @adojang 

Are you now sorted?

**Comment by adojang** [comment]
Hey Matthew, sorry for the late response, I'm sorted, thanks!
