### ISSUE TITLE
Undefined function results in error during setup

### ISSUE THREAD

**Issue by henklietaert** [mhzawadi/invoiceplane#25]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* ** please explain your *feature* or *bug* report**
When going through the setup process I get an error when clicking continue on the screen to create the user.

* **What is the current behavior?**
An error is thrown.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Error in the browser:
An uncaught Exception was encountered

Type: Error

Message: Call to undefined function Symfony\Polyfill\Mbstring\iconv_strlen()

Filename: /var/www/html/vendor/symfony/polyfill-mbstring/Mbstring.php

Line Number: 484

Backtrace:

File: /var/www/html/vendor/symfony/polyfill-mbstring/bootstrap.php
Line: 35
Function: mb_strlen

File: /var/www/html/application/libraries/MY_Form_validation.php
Line: 36
Function: run

File: /var/www/html/application/core/MY_Model.php
Line: 455
Function: run

File: /var/www/html/application/modules/setup/controllers/Setup.php
Line: 388
Function: run_validation

File: /var/www/html/index.php
Line: 325
Function: require_once

Line in the log:
10.1.15.8 - - [29/Sep/2023:09:23:54 +0000] "GET /favicon.ico HTTP/1.1" 499 0 "http://192.168.100.11:7003/index.php/setup/create_user" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0" "-"

* **What is the expected behavior?**

To continue in the registration process

* **What is the motivation / use case for changing the behavior?**

App is unable to function like this.

* **Please tell us about your environment:**
  
  - Version: latest tag on docker hub.
  - Browser: [all]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by mhzawadi** [comment]
Hello @henklietaert 

Could you have a look at the 1.6 version and see if that works please?
Also can you post your compose file?

**Comment by mhzawadi** [comment]
Hey @henklietaert 

A new 1.6 image has been pushed, does that have all the fixes in it you need?
If it does, please close this

**Comment by mhzawadi** [comment]
Closing as no reply
