### ISSUE TITLE
Container healthcheck

### ISSUE THREAD

**Issue by matt-horwood-mayden** [mhzawadi/invoiceplane#3]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* ** please explain your *feature* or *bug* report**

I would like a HealthCheck to make sure the container is working

* **What is the current behavior?**

Once the container has started docker then just makes sure it running

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

If the web service stops working, docker should make the container as unhealthy

* **What is the motivation / use case for changing the behavior?**
To see if the web service is working

* **Please tell us about your environment:**
  
  - Version: 2.0.0-beta.X
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by mhzawadi** [comment]
this is done
