### ISSUE TITLE
Only payment processor appears to be Stripe. Would like other options like PayPal.

### ISSUE THREAD

**Issue by dnburgess** [mhzawadi/invoiceplane#32]
* **I'm submitting a ...**
  - [*] bug report

* ** please explain your *feature* or *bug* report**
Only seeing Stripe Payment Processing. Would like to see others. Not sure how.

* **What is the current behavior?**
Only seeing Stripe Payment Processing. Would like to see others. Not sure how.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
more payment options being available

* **Please tell us about your environment:**
I'm using this: https://github.com/mhzawadi/invoiceplane/blob/master/stack-invoiceplane.yml

**Comment by mhzawadi** [comment]
Hi @dnburgess 

Thanks for your issue, I dont maintain the code for Invoiceplane. This is just a Docker image you can use.

Please see this page -> https://wiki.invoiceplane.com/en/1.6/settings/online-payments for why Stripe is the only option

**Comment by dnburgess** [comment]
Gotcha. thanks for the quick response. Will mark completed.
