### ISSUE TITLE
Make the whole config dockerized

### ISSUE THREAD

**Issue by the-hotmann** [mhzawadi/invoiceplane#39]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request

I am talking about the sed commands here: https://github.com/mhzawadi/invoiceplane/blob/master/setup/start.sh

There are two things here to do:

1. add all normal config parts (`ENABLE_DEBUG`, `REMOVE_INDEXPHP`, `SESS_EXPIRATION`, `SESS_MATCH_IP`, `ENABLE_INVOICE_DELETION`, `DISABLE_READ_ONLY`)
2. also add the critical 3 lower ones. (`ENCRYPTION_KEY`, `ENCRYPTION_CIPHER`, `SETUP_COMPLETED`)

I am very well aware, that the lower part of the config states: "DO NOT EDIT"

But this was not written there with docker in the back of the mind.

Also the later 3 shall JUST be replaced if env var `SETUP_COMPLETED` is true. If it is not true, they shall not be replaced anyway.

The SED script also shall be adjusted, so it does not replace lines when the ENV-Var is not set.

I thought of something like this:

```
if [ ! -f "/var/www/html/ipconfig.php" ]; then

    /var/www/html/ipconfig.php.example > /var/www/html/ipconfig.php

else

    [ -n "$IP_URL" ] && sed -i 's/IP_URL=/IP_URL=${IP_URL}/' /var/www/html/ipconfig.php
    [ -n "$ENABLE_DEBUG" ] && sed -i 's/ENABLE_DEBUG=/ENABLE_DEBUG=${ENABLE_DEBUG}/' /var/www/html/ipconfig.php
    [ -n "$DISABLE_SETUP" ] && sed -i 's/DISABLE_SETUP=/DISABLE_SETUP=${DISABLE_SETUP}/' /var/www/html/ipconfig.php
    [ -n "$REMOVE_INDEXPHP" ] && sed -i 's/REMOVE_INDEXPHP=/REMOVE_INDEXPHP=${REMOVE_INDEXPHP}/' /var/www/html/ipconfig.php

    [ -n "$DB_HOSTNAME" ] && sed -i 's/DB_HOSTNAME=/DB_HOSTNAME=${MYSQL_HOST}/' /var/www/html/ipconfig.php
    [ -n "$DB_USERNAME" ] && sed -i 's/DB_USERNAME=/DB_USERNAME=${DB_USERNAME}/' /var/www/html/ipconfig.php
    [ -n "$DB_PASSWORD" ] && sed -i 's/DB_PASSWORD=/DB_PASSWORD=${DB_PASSWORD}/' /var/www/html/ipconfig.php
    [ -n "$DB_DATABASE" ] && sed -i 's/DB_DATABASE=/DB_DATABASE=${DB_DATABASE}/' /var/www/html/ipconfig.php
    [ -n "$DB_PORT" ] && sed -i 's/DB_PORT=/DB_PORT=${DB_PORT}/' /var/www/html/ipconfig.php

    [ -n "$SESS_EXPIRATION" ] && sed -i 's/SESS_EXPIRATION=/SESS_EXPIRATION=${SESS_EXPIRATION}/' /var/www/html/ipconfig.php
    [ -n "$SESS_MATCH_IP" ] && sed -i 's/SESS_MATCH_IP=/SESS_MATCH_IP=${SESS_MATCH_IP}/' /var/www/html/ipconfig.php
    [ -n "$ENABLE_INVOICE_DELETION" ] && sed -i 's/ENABLE_INVOICE_DELETION=/ENABLE_INVOICE_DELETION=${ENABLE_INVOICE_DELETION}/' /var/www/html/ipconfig.php
    [ -n "$DISABLE_READ_ONLY" ] && sed -i 's/DISABLE_READ_ONLY=/DISABLE_READ_ONLY=${DISABLE_READ_ONLY}/' /var/www/html/ipconfig.php

    ### CRITICAL
    if [ -n "$SETUP_COMPLETED" ]; then
        [ -n "$ENCRYPTION_KEY" ] && sed -i 's/ENCRYPTION_KEY=/ENCRYPTION_KEY=${ENCRYPTION_KEY}/' /var/www/html/ipconfig.php
        [ -n "$ENCRYPTION_CIPHER" ] && sed -i 's/ENCRYPTION_CIPHER=/ENCRYPTION_CIPHER=${ENCRYPTION_CIPHER}/' /var/www/html/ipconfig.php
        sed -i 's/SETUP_COMPLETED=/SETUP_COMPLETED=${SETUP_COMPLETED}/' /var/www/html/ipconfig.php
    fi
fi
```

What are the benefits of this?

1. fully configurable
2. even the encryption key can be set (now `ipconfig.php` does not have to be peristent anymore)

How to use this?

1. set ALL Variables BUT `SETUP_COMPLETED`
2. complete the setup
3. read the `ipconfig.php` file and also set `ENCRYPTION_KEY` & `ENCRYPTION_CIPHER` in the docker-compose.yml
4. recreate container
5. Use container.

With this approach the admin has full control over InvoicePlane.

Keep in mind, this snippet was not tested by my. But should be alright.

**Comment by mhzawadi** [comment]
Thanks for your feature request, will have a look at this and see what I can do.

**Comment by mhzawadi** [comment]
Evening @the-hotmann 

I have news, after making some changes to the build and startup process. This is now ready for testing, the dev image has all the changes in it.

Also PR #40 has all the changes ready for merge, if the readme makes sense to you will merge once your happy.

If you have readme feedback please add it to this issue or the PR

**Comment by the-hotmann** [comment]
@mhzawadi thanks lok about right!

Very happy with it so far. If you publish it, please publish it with a the dev tag, so people can test it and report back.
Since these are structural changes take a little time untill you merge this into default version-tags.

Thanks!

P.S.: once it is published I will test it and report back if it worked - then we can close this issue.

**Comment by mhzawadi** [comment]
Morning @the-hotmann 

The dev image has the changes in it already, I have a GitHub action to build the dev image on opening a PR

**Comment by mhzawadi** [comment]
PR merged, closing
