### ISSUE TITLE
I want to backdate a new/draft invoice

### ISSUE THREAD

**Issue by xeroc** [mhzawadi/invoiceplane#41]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a**
  - [x] bug report
  - [ ] feature request

* ** please explain your *feature* or *bug* report**

When i have a draft invoice with an invoice date X and send out an email tot he client, the invoice us changed to invoice date Y (Y being today).

* **What is the motivation / use case for changing the behavior?**

I create invoices on one date and have them confirmed by staff. However, I want invoices to be dated at the last day of the month, even if I only manage to send them out 2 days later.

**Comment by mhzawadi** [comment]
Hi @xeroc 

Could you post this to the InvoicePlane Github repo please?

https://github.com/InvoicePlane/InvoicePlane/issues

**Comment by xeroc** [comment]
Woopsy, sorry
