### ISSUE TITLE
Restart of InvoicePlane appends data to the ipconfig.php

### ISSUE THREAD

**Issue by SvenKribitz** [mhzawadi/invoiceplane#48]
This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* ** please explain your *feature* or *bug* report**

The page doesn't load, instead there's errors thrown because a connection to the database couldn't be established.
The ipconfig.php is getting duplicated values:
![image](https://github.com/user-attachments/assets/6e3569f6-e9e4-4497-a119-0551658c0618)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Installed it on Portainer in a stack:

`services:
  invoiceplane:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    hostname: invoiceplane
    image: mhzawadi/invoiceplane:v1.6.1.2
    container_name: invoiceplane
    ports:
      - '3217:80'
    volumes:
      - invoiceplane_data:/var/www/html
    environment:
      - DB_HOST=invoiceplane_db
      - DB_PORT=3306
      - DB_USER=name
      - DB_PASS=pw
      - DB_NAME=invoiceplane
      - IP_URL=http://server.local:3217
      - HOST_URL=server.local:3217
    networks:
      - invoiceplane_network

  db:
    hostname: invoiceplane_db
    image: mysql:8.0
    container_name: invoiceplane_db
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=invoiceplane
      - MYSQL_USER=name
      - MYSQL_PASSWORD=pw
    networks:
      - invoiceplane_network

volumes:
  invoiceplane_data:
  db_data:

networks:
  invoiceplane_network:
`

volumes:
invoiceplane_data:
db_data:

* **What is the expected behavior?**

When I restart the application it should do fine.

* **What is the motivation / use case for changing the behavior?**

Otherwise it breaks every restart

**Comment by mhzawadi** [comment]
oh, will try and have a look this week

**Comment by mhzawadi** [comment]
Hey @SvenKribitz 

I have jusyt pushed a fix to my dev image `mhzawadi/invoiceplane:dev`, could you test that and let me know if that fixes this issue. I can then update the latest image

**Comment by SvenKribitz** [comment]
Good evening, 
just tried it and ran into a ton of PHP errors.

Like this one:

A PHP Error was encountered
Severity: 8192

Message: Creation of dynamic property CI::$hooks is deprecated

Filename: core/Controller.php

Line Number: 83

Backtrace:

File: /var/www/html/application/third_party/MX/Base.php
Line: 62
Function: __construct

File: /var/www/html/application/third_party/MX/Base.php
Line: 67
Function: __construct

File: /var/www/html/application/third_party/MX/Controller.php
Line: 4
Function: require

File: /var/www/html/application/third_party/MX/Modules.php
Line: 172
Function: include_once

Message: Creation of dynamic property CI::$hooks is deprecated

File: /var/www/html/application/core/Base_Controller.php
Line: 18
Function: autoload

File: /var/www/html/application/third_party/MX/Modules.php
Line: 180
Function: include_once

File: /var/www/html/application/core/User_Controller.php
Line: 18
Function: autoload

File: /var/www/html/application/third_party/MX/Modules.php
Line: 180
Function: include_once

File: /var/www/html/application/core/Admin_Controller.php
Line: 18
Function: autoload

File: /var/www/html/application/third_party/MX/Modules.php
Line: 180
Function: include_once

File: /var/www/html/application/modules/dashboard/controllers/Dashboard.php
Line: 16
Function: autoload

File: /var/www/html/index.php
Line: 329
Function: require_once

**Comment by mhzawadi** [comment]
yeah, thats very bust. editing the main image now

**Comment by SvenKribitz** [comment]
Much appreciated. :-)

**Comment by SvenKribitz** [comment]
The dev image might be broken but you fixed it on the latest version. The issue is gone. I can restart the container without any issues now. Thank you!

**Comment by mhzawadi** [comment]
great news, might revert the PHP81 to PHP82 mess
