### ISSUE TITLE
container wont start

### ISSUE THREAD

**Issue by Cronus89** [mhzawadi/invoiceplane#5]
nginx: [emerg] directive "set" is not terminated by ";" in /etc/nginx/conf.d/default.conf:17
2021/06/24 20:12:25 [emerg] 1#1: directive "set" is not terminated by ";" in /etc/nginx/conf.d/default.conf:17

Looked at your configs in the repo and it indeed is missing a terminating ;

**Comment by mhzawadi** [comment]
very sorry, for that. Have built a new latest image, that should fix it.

Need to refactor the build process 😩

**Comment by Cronus89** [comment]
New error.

2021/06/28 15:10:32 [emerg] 1#1: unknown directive "if($http_x_forwarded_host" in /etc/nginx/conf.d/default.conf:17
nginx: [emerg] unknown directive "if($http_x_forwarded_host" in /etc/nginx/conf.d/default.conf:17

**Comment by mhzawadi** [comment]
good spot, have fixed that and other errors and have booted it without error.

its building now, if it works let me know and I can tag it

**Comment by mhzawadi** [comment]
the new tag (1.5.11.2) is live, closing this now

Please reopen if you still have issues
