### ISSUE TITLE
docker-compose up getting system up but index.php not there..

### ISSUE THREAD

**Issue by willthrom** [mhzawadi/invoiceplane#51]
**Describe the bug**

**To Reproduce**
curl https://github.com/mhzawadi/invoiceplane/blob/master/docker-compose.yml
edit docker-compose to change the port from 80 to 8090 : - "8090:80"     # The HTTP port
docker-compose up -d

**Expected behavior**
able to go to http://localhost:8090/index.php/setup

Getting 404.. Is this url wrong??

**Screenshots**

**Desktop (please complete the following information):**
latest
Linux
Opera

**Comment by willthrom** [comment]
I honestly feel stupid... because I am assuming this should be a straight process...

**Comment by mhzawadi** [comment]
Hello 👋🏼 

I have just tested your issue and your right, the first page load is a 404 error. But a refresh then shows the setup page.

There could be a 10 to 15 second delay in getting the setup page

**Comment by willthrom** [comment]
could you confirm what is the setup page? or the landing page?

I have tried to refresh dozens of times.. and not sure what else to do..

**Comment by mhzawadi** [comment]
I have just realised why your getting the error, its because your looking at traefik and it needs the right URL. I have just added the below that migh thelp, if you need more/better ward please let me know.

```
#### Using the traefik proxy

If you use the above compose file, you will need to update your `/etc/hosts` file.
you will need to add `127.0.0.1 invoiceplane.docker.local` to it in order that traefik does its routing, else you will get a `404` error page.
```

**Comment by willthrom** [comment]
and what page should I try to navigate to?

**Comment by mhzawadi** [comment]
if you have your `/etc/hosts` file setup, then `http://localhost:8090/index.php/setup` should work

**Comment by willthrom** [comment]
cool, now with the right config I could configure it to be accessible externally (DNS).

Thanks.

This is my final version:


version: '3.5'

volumes:
  invoiceplane_uploads:
  invoiceplane_css:
  invoiceplane_views:
  mariadb_10_4:

services:
  proxyv2:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"       # HTTP
      - "--entrypoints.websecure.address=:443" # HTTPS
    ports:
      - "8090:80"     # External HTTP port mapped to 80
      - "444:443"     # External HTTPS port
      - "8181:8080"   # Traefik Web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"

  invoiceplane:
    image: mhzawadi/invoiceplane
    volumes:
      - invoiceplane_uploads:/var/www/html/uploads
      - invoiceplane_css:/var/www/html/assets/core/css
      - invoiceplane_views:/var/www/html/application/views
    environment:
      - TZ=utc
      - MYSQL_HOST=mariadb_10_4
      - MYSQL_USER=invoiceplane
      - MYSQL_PASSWORD=invoiceplane
      - MYSQL_DB=invoiceplane
      - IP_URL=http://example.com:8090
      - REMOVE_INDEXPHP=true
      - SETUP_COMPLETED=false
    labels:
      - "traefik.http.routers.invoiceplane.rule=Host(`example.com`)"
      - "traefik.http.routers.invoiceplane.entrypoints=web"
      - "traefik.http.services.invoiceplane.loadbalancer.server.port=80"

  mariadb_10_4:
    image: mariadb:10.4.10
    volumes:
      - mariadb_10_4:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_password
      - MYSQL_DATABASE=invoiceplane
      - MYSQL_USER=invoiceplane
      - MYSQL_PASSWORD=invoiceplane
    labels:
      - "traefik.enable=false"
