### ISSUE TITLE
Change default port 80

### ISSUE THREAD

**Issue by fr3d02** [mhzawadi/invoiceplane#8]
Hello,

I can't change default port (80) when i config (Run or docker-compose). I"ve tested other version of docker (And other tag in your build) but same result. When i change port, i'm redirected to https://127.0.0.1/welcome. I've test on other computer and same result. Have you a solution ?

Thx

**Comment by mhzawadi** [comment]
Hello 👋🏼 

when you docker run with `-p 8080:80`, does it work? as the right hand port is in the container and it only listens on port 80.

If your wanting to have it on SSL/TLS, you will need to have a proxy server in front of it

**Comment by fr3d02** [comment]
When i test with 80:80, no problems. When i test with 12345:80 or other not working. I just testing without SSL TLS ou HTTPS.

docker run --name invoiceplane-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -v /my_dir/invoiceplane:/var/lib/mysql -d mysql:5.6
docker run -ti -d -p 12345:80 --name invoiceplane --link invoiceplane-mysql:mysql mhzawadi/invoiceplane

Just testing this 2 commands and not working for me...

**Comment by mhzawadi** [comment]
I have good news, I have your run command working.
If you use a non-standard port, you need to set the `IP_URL` to the full URL (including port).

docker run --name invoiceplane-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -v /my_dir/invoiceplane:/var/lib/mysql -d mysql:5.6
docker run -ti -d -p 12345:80 `-e IP_URL=http://127.0.0.1:12345` --name invoiceplane --link invoiceplane-mysql:mysql mhzawadi/invoiceplane

**Comment by fr3d02** [comment]
Perfect ! Very good, thx a lot. I'm little noob...!
Have a good day !
