### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by chikko80** [mhzawadi/invoiceplane#9]
Hey,

i tried your docker-compose file but the only thing i get is 404 error no matter what page i go to (/, /index.php, index.php/setup).
Do you have any advice?

Logs say 307:

invoiceplane_1  | 127.0.0.1 - - [13/Feb/2022:10:34:35 +0000] "GET /index.php HTTP/1.1" 307 5 "-" "curl/7.79.1" "-"

Thanks

**Comment by mhzawadi** [comment]
Hello 👋🏼 

Thanks for trying out my image, sorry your having issues. from the looks of it, traefik will only pass `invoiceplane.docker.local` to the container. This can be changed in the compose file if you want a proper URL.

For testing, add `127.0.0.1    invoiceplane.docker.local` to your `/etc/hosts` file and see if you get the site

**Comment by chikko80** [comment]
Hey @mhzawadi 

i don't run the image local. It should run on my remote server behind my main nginx reverse proxy and it should be addressed by a specific subdomain.

I tried to change the IP_URL to https://subdomain.domain.topleveldomain and the label for traefik to subdomain.domain.topleveldomain but i couldn't get it to work.

**Comment by mhzawadi** [comment]
thats very odd, are you using traefik? or are you using ports on your containers?

If your using ports, you will need add the ports.
If your using traefik, can you see the service in the webUI?

**Comment by mhzawadi** [comment]
Hi @chikko80,

are you still having issues?
